version: '3'
services:
    nginx:
      image: nginx
      container_name: nginx
      volumes:
        - ./templates:/etc/nginx/templates
        - ./nginx/:/etc/nginx/conf.d/
      ports: 
        - "8080:80"
   
    db:
      image: mysql:latest
      container_name: mysql
      volumes:
        - 
      restart: always

    wordpress:
      depends_on:
        - db
      container_name: wordpress
      image: wordpress:latest
      volumes:
        -
      ports:
       - "8000:80"
       #- "443:443"
      restart: always
      environment:
        WORDPRESS_DB_HOST: 
        WORDPRESS_DB_USER: user
        WORDPRESS_DB_PASSWORD: Qwerty1!
        WORDPRESS_DB_NAME: wordpress 