version: '3'
services:
    nginx:
      image: nginx
      container_name: nginx
      volumes:
        - ./templates:/etc/nginx/templates
        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - wp_data:/var/www/html
        - dbdata:/var/lib/mysql
      ports: 
        - "80:80"
      depends_on:
        - wordpress
        - db
   
    db:
      image: mysql:latest
      container_name: mysql
      volumes:
        - dbdata:/var/lib/mysql
        - ./mysql/mysql.cnf:/etc/mysql/mysql.cnf
      restart: always
      environment:
        MYSQL_DATABASE: wordpress
        MYSQL_ROOT_PASSWORD: Qwerty1!
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql

    wordpress:
      depends_on:
        - db
      container_name: wordpress
      image: wordpress:latest
      volumes:
        - wp_data:/var/www/html
      #volumes:
      #  - 
      ports:
        - "8000:80"
      # - "443:443"
      restart: always
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
volumes:
  dbdata:
    driver: local
  wp_data: